name: Java CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Setup JavaFX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjfx

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          export JAVAFX_MODULES_PATH=/usr/share/openjfx/lib
          ./gradlew build --info \
            -Pjavafx.modules.path=$JAVAFX_MODULES_PATH \
            -Dorg.gradle.java.home=/usr/lib/jvm/java-17-temurin-amd64 \
            -Djavafx.platform=linux

      - name: Run Checkstyle
        run: |
          ./gradlew checkstyleMain
          ./gradlew checkstyleTest
