name: Java CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install OpenJFX
        run: |
          sudo apt-get update
          sudo apt-get install -y openjfx

      - name: Build with Gradle
        env:
          GRADLE_OPTS: "--module-path /usr/share/openjfx/lib --add-modules=javafx.controls,javafx.fxml,javafx.graphics"
        run: ./gradlew build

      - name: Checkstyle on main code
        run: ./gradlew checkstylemain

      - name: Checkstyle on test code
        run: ./gradlew checkstyletest
